version: '3.8'

services:
  front:
    build: ./front
    ports:
      - "5000:5000"
    depends_on:
      - core

  core:
    build: ./core
    ports:
      - "5001:5001"

  load_tester:
    build: ./load_tester
    depends_on:
      - front

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin    

volumes:
  grafana-data: